# Generated by Django 3.1.3 on 2021-02-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2x',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
