# Generated by Django 3.1.2 on 2020-10-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20201029_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
