# Generated by Django 3.1.2 on 2020-10-29 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='post_bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
