# Generated by Django 3.1.2 on 2020-10-29 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20201029_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='post_bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
