# Generated by Django 3.1.2 on 2020-10-31 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201031_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='candidate',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_candidate', to='posts.candidate'),
        ),
    ]
