# Generated by Django 3.1.2 on 2020-11-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20201111_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='main_question',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
