# Generated by Django 3.1.2 on 2020-11-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20201111_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
