# Generated by Django 3.1.2 on 2020-11-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_category_hero_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hero_img',
            field=models.FileField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
