# Generated by Django 3.1.2 on 2020-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20201111_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hero_img',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
