# Generated by Django 3.1.2 on 2020-11-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20201111_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
