# Generated by Django 3.1.2 on 2020-11-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
