# Generated by Django 3.1.3 on 2020-11-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20201116_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_description',
            field=models.TextField(blank=True, default='', max_length=350, null=True),
        ),
    ]
