# Generated by Django 3.1.3 on 2020-11-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_post_feature_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='feature_description',
            new_name='feature_summary',
        ),
    ]
