# Generated by Django 3.1.3 on 2020-11-21 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_featuredmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredmessage',
            old_name='feature',
            new_name='featured',
        ),
    ]
